services:
  postgres:
    container_name: postgres
    image: postgres:16.8-alpine3.20
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    ports:
      - '5432:5432'