# Generated by Django 5.2 on 2025-05-06 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_care_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarevent',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
