# Generated by Django 5.2 on 2025-05-03 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pet_care_app', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            # SQL, що видаляє стовпці, якщо вони є
            sql="""
                    ALTER TABLE pet_care_app_user
                      DROP COLUMN IF EXISTS is_staff,
                      DROP COLUMN IF EXISTS is_superuser,
                      DROP COLUMN IF EXISTS last_login;
                """,
            # у зворотному напрямі нічого не робимо
            reverse_sql=migrations.RunSQL.noop
        ),
    ]
