# Generated by Django 5.2 on 2025-05-07 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pet_care_app', '0002_calendarevent_completed'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='calendarevent',
            table='CalendarEvent',
        ),
        migrations.AlterModelTable(
            name='forumcomment',
            table='ForumComment',
        ),
        migrations.AlterModelTable(
            name='forumlike',
            table='ForumLike',
        ),
        migrations.AlterModelTable(
            name='forumpost',
            table='ForumPost',
        ),
        migrations.AlterModelTable(
            name='journalentry',
            table='JournalEntry',
        ),
        migrations.AlterModelTable(
            name='pet',
            table='Pet',
        ),
        migrations.AlterModelTable(
            name='sitepartner',
            table='SitePartner',
        ),
        migrations.AlterModelTable(
            name='user',
            table='User',
        ),
    ]
