# Generated by Django 5.2 on 2025-05-03 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_care_app', '0003_alter_user_photo_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo_url',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=''),
        ),
    ]
