# Generated by Django 5.2 on 2025-05-07 17:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_care_app', '0003_alter_calendarevent_table_alter_forumcomment_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarevent',
            name='event_type',
            field=models.CharField(choices=[('CHECKUP', 'Огляд у ветеринара'), ('VACCINATION', 'Вакцинація'), ('FLEA_CTRL', 'Обробка від бліх/кліщів'), ('GROOMING', 'Грумінг'), ('BATH', 'Купання'), ('TRAINING', 'Тренування'), ('OTHER', 'Інше')], default='OTHER', max_length=20),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='entry_type',
            field=models.CharField(choices=[('CHECKUP', 'Огляд у ветеринара'), ('VACCINATION', 'Вакцинація'), ('FLEA_CTRL', 'Обробка від бліх/кліщів'), ('GROOMING', 'Грумінг'), ('BATH', 'Купання'), ('TRAINING', 'Тренування'), ('OTHER', 'Інше')], default='OTHER', max_length=20),
        ),
        migrations.AlterField(
            model_name='calendarevent',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
