# Generated by Django 5.2 on 2025-05-07 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_care_app', '0004_calendarevent_event_type_journalentry_entry_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitepartner',
            name='partner_type',
            field=models.CharField(choices=[('CLINIC', 'Ветеринарна клініка'), ('GROOMING_SALON', 'Грумінг-салон'), ('PET_STORE', 'Зоомагазин')], default='PET_STORE', max_length=20),
        ),
        migrations.AddField(
            model_name='sitepartner',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=3),
        ),
    ]
