# Generated by Django 5.2 on 2025-05-09 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_care_app', '0006_remove_sitepartner_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumpost',
            name='post_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
