# Generated by Django 5.2 on 2025-05-09 14:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_care_app', '0007_alter_forumpost_post_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerWatchlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_watchlists', to='pet_care_app.sitepartner')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_watchlist', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'PartnerWatchlist',
                'unique_together': {('user', 'partner')},
            },
        ),
    ]
