# Generated by Django 5.2 on 2025-05-09 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pet_care_app', '0008_partnerwatchlist'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='partnerwatchlist',
            table='SitePartnerWatchlist',
        ),
    ]
