# Generated by Django 5.2 on 2025-05-09 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pet_care_app', '0009_alter_partnerwatchlist_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partnerwatchlist',
            name='created_at',
        ),
    ]
