# Generated by Django 5.2 on 2025-05-10 18:03

import pet_care_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_care_app', '0010_remove_partnerwatchlist_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='birthday',
            field=models.DateField(validators=[pet_care_app.models.validate_birthday]),
        ),
        migrations.AddConstraint(
            model_name='forumpost',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('post_text__isnull', False), models.Q(('post_text', ''), _negated=True)), models.Q(('photo_url__isnull', False), models.Q(('photo_url', ''), _negated=True)), _connector='OR'), name='post_text_or_photo'),
        ),
    ]
