# Generated by Django 5.2 on 2025-05-10 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pet_care_app', '0011_alter_pet_birthday_forumpost_post_text_or_photo'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='forumpost',
            name='post_text_or_photo',
        ),
    ]
