# Generated by Django 5.2 on 2025-05-12 16:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_care_app', '0012_remove_forumpost_post_text_or_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarevent',
            name='start_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterModelTable(
            name='calendarevent',
            table='Calendar_events',
        ),
        migrations.AlterModelTable(
            name='forumcomment',
            table='Forum_comments',
        ),
        migrations.AlterModelTable(
            name='forumlike',
            table='Forum_likes',
        ),
        migrations.AlterModelTable(
            name='forumpost',
            table='Forum_posts',
        ),
        migrations.AlterModelTable(
            name='journalentry',
            table='Journal_entries',
        ),
        migrations.AlterModelTable(
            name='partnerwatchlist',
            table='Watchlists',
        ),
        migrations.AlterModelTable(
            name='pet',
            table='Pets',
        ),
        migrations.AlterModelTable(
            name='sitepartner',
            table='Partner_sites',
        ),
        migrations.AlterModelTable(
            name='user',
            table='Users',
        ),
    ]
