# Generated by Django 5.2 on 2025-05-14 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pet_care_app', '0013_alter_calendarevent_start_date_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='partnerwatchlist',
            table='Watchlist_entries',
        ),
    ]
